on:
  push:
    branches: [master, "release/*"]
    paths:
      - ".github/workflows/ci-circleci.yml"
      - ".circleci/config.yml"
      - "requirements/pytorch/**"
      - "src/pytorch_lightning/**"
      - "tests/tests_pytorch/**"
      - "setup.cfg"  # includes pytest config
  # should use `pull_request_target` but it's blocked by
  # https://github.com/CircleCI-Public/trigger-circleci-pipeline-action/issues/27
  # so this job will not run on forks until the above is fixed or we replace CircleCI for another provider
  pull_request:
    branches: [master, "release/*"]
    paths:
      - ".github/workflows/ci-circleci.yml"
      - ".circleci/config.yml"
      - "requirements/pytorch/**"
      - "src/pytorch_lightning/**"
      - "tests/tests_pytorch/**"
      - "setup.cfg"  # includes pytest config

jobs:
  # https://github.com/marketplace/actions/trigger-circleci-pipeline
  trigger-circleci:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'Lightning-AI/lightning' }}  # skip for forks as secrets cannot be shared
    steps:
      - uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0.6
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
        with:
          GHA_Meta: ${{ github.event.pull_request.number }}
